# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=3000
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
          - --allow-multiple-documents
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
